
@baseUrl = http://localhost:3000
@authToken = {{authenticate.response.body.accessToken}}

### AppControllerGetHello

### tipo de método -> url -> recurso da URL

# @name AppControllerGetHello
GET {{baseUrl}}/home/hello/
###

#Recados
###Lista todos os recados
GET {{baseUrl}}/recados/
?limit=10
&offset=10



### Lista 1 recado
GET {{baseUrl}}/recados/2/

### Cria uma recado
POST {{baseUrl}}/recados/
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "texto": "Um recado apenas",
    "paraId": 6
}
### Atualiza um recado
PATCH  {{baseUrl}}/recados/2/
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "texto": "ATUALIZA Recado",
    "lido": true
}

### Apaga um recado
DELETE {{baseUrl}}/recados/2/
Authorization: Bearer {{authToken}}

### Query parameter sao usados nas urls depois de "?" 
###assim identificando qual e um parâmetro de Query parameter


#Pessoas
###Lista todas as Pessoas
GET {{baseUrl}}/pessoas/
?limit=10
&offset=10
Authorization: Bearer {{authToken}}

### Lista 1 pessoa
GET {{baseUrl}}/pessoas/6/
Authorization: Bearer {{authToken}}


### Cria uma pessoa
POST {{baseUrl}}/pessoas/
Content-Type: application/json

{
    "email": "lucas@email.com",
    "senha": "123456",
    "name": "Lucas"
}
### Atualiza uma pessoa
PATCH  {{baseUrl}}/pessoas/4/
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "name": "Lukas",
    "senha": "1234567"
}

### Apaga uma pessoa
DELETE {{baseUrl}}/pessoa/2/
Authorization: Bearer {{authToken}}


#Auth
###Login
# @name authenticate
POST {{baseUrl}}/auth/
Content-Type: application/json

{
    "email": "lucas@email.com",
    "password": "123456"
}

