
@baseUrl = http://localhost:3000

### AppControllerGetHello

### tipo de metodo -> url -> recurso da URL

# @name AppControllerGetHello
GET {{baseUrl}}/home/hello/
###

# @name Exemploderota
GET {{baseUrl}}/home/exemplo/

### ConceitosManualController 

# @name ConceitosManualController 
GET {{baseUrl}}/conceitos-manual/

### ConceitosAutomaticoController 

# @name ConceitosManualController 
GET {{baseUrl}}/conceitos-automatico/

###
#Recados
GET {{baseUrl}}/recados/

###
GET {{baseUrl}}/recados/1/