
@baseUrl = http://localhost:3000

### AppControllerGetHello

### tipo de metodo -> url -> recurso da URL

# @name AppControllerGetHello
GET {{baseUrl}}/home/hello/
###

#Recados
###Lista todos os recados
GET {{baseUrl}}/recados/
?limit=10
&offset=10


### Lista 1 recado
GET {{baseUrl}}/recados/2/

### Cria uma recado
POST {{baseUrl}}/recados/
Content-Type: application/json

{
    "texto": "Novo Recado",
    "de": "Joana",
    "para": "João",
    "lido": false,
    "data": "2025-04-17T13:31:20.021Z"
}
### Atualiza um recado
PATCH  {{baseUrl}}/recados/2/
Content-Type: application/json

{
    "texto": "ATUALIZA Recado",
}

### Apaga um recado
DELETE {{baseUrl}}/recados/2/

### Query parameter sao usados nas urls depois de "?" 
###assim identificando qual e um parametro de Query parametyer